# Generated by Django 4.2.4 on 2023-09-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_SAC', '0004_atendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao_Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('data_hora', models.DateTimeField()),
                ('id_atendimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='App_SAC.atendimento', verbose_name='Atendimento')),
                ('id_situacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='situacoes', to='App_SAC.situacao', verbose_name='Situacao')),
            ],
        ),
    ]
